### ISSUE TITLE
[Question] Custom signs on posts

### ISSUE THREAD

**Issue by Zthingman181** [MLG-Fortress/PopulationDensity#7]
I'm currently having problems writing the custom signs. None of the text I put in is showing up, I assume I am using bad syntax or not reloading/restarting properly, so a quick sanity check shouldn't hurt.
A copy of the last log is attached and config is pasted below.

Any help is appreciated.

[edit: sadly I cant get the bbcode and singlequotes to not conflict either...]
OS; windows 10 64bit
spigot server version: git-Spigot-5391d73-0ebb9c7 (MC: 1.10.2) (API Version 1.10.2-R0.1-SNAPSHOT)
java version: java 8 update 101 (64bit)
[latest.txt](https://github.com/TechFortress/PopulationDensity/files/507023/latest.txt) server log

``` yml
  populationDensity:
  NewPlayersSpawnInHomeRegion: true
  RespawnInHomeRegion: true
  CityWorldName: ''
  AllowTeleportation: true
  TeleportFromAnywhere: false
  MaxDistanceFromSpawnToUseHomeRegion: 25
  ManagedWorldName: world
  DensityRatio: 1.0
  MaxIdleMinutes: 10
  LoginQueueEnabled: true
  ReservedSlotsForAdministrators: 1
  LoginQueueMessage: '%queuePosition% of %queueLength% in queue.  Reconnect within
    3 minutes to keep your place.  :)'
  HoursBetweenScans: 6
  BuildRegionPosts: true
  NewestRegionRequiresPermission: false
  GrassRegrows: true
  AnimalsRespawn: true
  TreesRegrow: true
  Max Monsters Nearby For More To Spawn: 2
  ThinOvercrowdedAnimalsAndMonsters: true
  Abandoned Farm Animals Die: true
  Unused Minecarts Vanish: true
  Mark Removed Animal Locations With Shrubs: true
  Remove Wild Skeletal Horses: true
  Disable Monster Grinders When Lagging: true
  Maximum Hoppers Per Chunk: 10
  Boot Idle Players When Lagging: true
  Capture Spigot Timings When Lagging: false
  KeepSpawnRegionPostLoaded: true
  KeepAllRegionPostsLoaded: false
  MinimumRegionPostY: 62
  PreciseWorldSpawn: false
  MinimumWoodAvailableToPlaceNewPlayers: 200
  MinimumResourceScoreToPlaceNewPlayers: 200
  PostProtectionDistance: 2
  Maximum Region Name Length: 10
  PostDesign:
    TopBlock: '89:0'
    PostBlocks: '89:0'
    PlatformOuterRing: '98:0'
    PlatformInnerRing: '98:0'
  Region Name List:
  - redstone
  - dew
  - creeper
  - sword
  - wintersebb
  - fjord
  - vista
  - breeze
  - tide
  - stream
  - glenwood
  - journey
  - cragstone
  - pickaxe
  - axe
  - hammer
  - anvil
  - mist
  - sunrise
  - sunset
  - copper
  - coal
  - shovel
  - minecart
  - railway
  - dig
  - chasm
  - basalt
  - agate
  - boat
  - grass
  - gust
  - ruby
  - emerald
  - stone
  - peak
  - ore
  - boulder
  - hilltop
  - horizon
  - fog
  - cloud
  - canopy
  - gravel
  - torch
  - obsidian
  - treetop
  - storm
  - gold
  - canopy
  - leaf
  - summit
  - glade
  - trail
  - seed
  - diamond
  - armor
  - sand
  - flint
  - field
  - steel
  - helm
  - gorge
  - campfire
  - workshop
  - rubble
  - iron
  - chisel
  - moon
  - shrub
  - zombie
  - stem
  - vale
  - pumpkin
  - lantern
  - copper
  - moonBeam
  - soil
  - dust
  CustomSigns:
    Main:
    - ''
    - Population
    - Density
    - ''
    North:
    - testn1
    - testn2
    - testn3
    - testn4
    South:
    - tests1
    - tests2
    - tests3
    - tests4
    East:
    - teste1
    - teste2
    - teste3
    - teste4
    West:
    - testw1
    - testw2
    - testw3
    - testw4
```
